version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    labels:
      - "dependencies"
      - "github-actions"
    schedule:
      interval: "monthly"

  - package-ecosystem: "pub"
    directory: "/"
    labels:
      - "dependencies"
    schedule:
      interval: "monthly"